// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pwkrbvuahighligsgjav.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB3a3JidnVhaGlnaGxpZ3NnamF2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU0NzQzNzksImV4cCI6MjA2MTA1MDM3OX0.M76z7k09hIUW_k6MwcT6iKbH6CpSbsHRPgKRUbXl3nI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);